application:
  queueName: [QUEUE]

amqphub:
  amqp10jms:
    username: [USERNAME]
    password: [PASSWORD]
    remote-url: amqps://[ENDPOINT]
    #remote-url: amqpwss://[ENDPOINT]:443 # I want to do this

logging:
  level:
    org.apache.qpid.jms: info
    org.springframework.jms: info
    org.amqphub.spring: info
